name: Patch Fiddler Everywhere

on:
  workflow_call:
    inputs:
      fe_version:
        type: string
        description: "FE Version to be Patched"
        required: true

jobs:
  patch_fe:
    runs-on: windows-latest

    env:
      PATCHING_VERSION: ${{ inputs.fe_version }}

    outputs:
      patched-fe-name: ${{ steps.rename-fe.outputs.patched-fe-name }}
      
    steps:
      - name: Download Yukuhana-Patch
        uses: actions/download-artifact@v4
        with:
          name: yukihana-patch
          path: yukihana-patch

      - name: Download msojocs-Server
        uses: actions/download-artifact@v4
        with:
          name: msojocs-patch
          path: msojocs-patch

      - name: Download FE
        uses: actions/download-artifact@v4
        with:
          name: fe_app64
          path: fe_app64

      - name: List the contents of the downloaded artifacts
        run: |
          Get-ChildItem -Recurse yukihana-patch
          Get-ChildItem -Recurse msojocs-patch
          Get-ChildItem -Recurse fe_app64
        shell: pwsh

      - name: Rename main FE folder
        run: Rename-Item -Path "fe_app64" -NewName "FE"

      - name: Patch fiddler.dll / libfiddler.dll
        run: |
          $original_fiddler = "FE/${{ needs.download-yukihana-patch.outputs.yukihana-fiddler-name }}.dll"
          $yukihana_fiddler = "yukihana-patch/${{ needs.download-yukihana-patch.outputs.yukihana-fiddler-name }}.dll"
          
          if ((Test-Path $original_fiddler) -and (Test-Path $yukihana_fiddler)) {
            Copy-Item -Path $yukihana_fiddler -Destination $original_fiddler -Force
            Write-Host "Replaced $original_fiddler with $yukihana_fiddler"
          } else {
            Write-Host "fiddler / libfiddler or yukihana patch not found"
          }
        shell: pwsh

      - name: Patch hostpolicy.dll
        run: |
          $original_hostpolicy = "FE/resources/app/out/WebServer/hostpolicy.dll"
          $original_copy_hostpolicy = "FE/resources/app/out/WebServer/hostpolicy.original.dll"
          $yukihana_hostpolicy = "yukihana-patch/hostpolicy.dll"

          if ((Test-Path $original_hostpolicy) -and (Test-Path $yukihana_hostpolicy)) {
            Move-Item -Path $original_hostpolicy -Destination $original_copy_hostpolicy
            Copy-Item -Path $yukihana_hostpolicy -Destination $original_hostpolicy
            Write-Host "Renamed $original_fiddler with $original_copy_hostpolicy & Applied Yukihana Patch"
          } else {
            Write-Host "original hostpolicy.dll or yukihana hotstpolicy not found"
          }

      - name: Clean yukihana-patch
        run: |
          if (Test-Path yukihana-patch) {
            Remove-Item -Path "yukihana-patch" -Recurse
          } else {
            Write-Host "yukihana-patch Folder not found"
          }

      - name: Copy Server Folder
        run: |
          $source_server_folder = "msojocs-patch/server/file"
          $destination_server_folder = "FE/resources/app/out"
          
          if (Test-Path $source_server_folder) {
            Copy-Item -Path $source_server_folder -Destination $destination_server_folder -Recurse
          } else {
            Write-Host "Source Server Folder not found"
          }
        shell: pwsh

      - name: Patch main.js to main.original.js
        run: |
          $source_main = "FE/resources/app/out/main.js"
          $main_content = Get-Content -Path $source_main -Raw

          $new_main = "FE/resources/app/out/main.original.js"

          $source_index = "msojocs-patch/server/index.js"
          $index_content = Get-Content -Path $source_index -Raw
          
          if ((Test-Path $source_main) -and (Test-Path $source_index)) {
            Copy-Item -Path $source_main -Destination $new_main

            $appended_content = $index_content + $main_content

            Set-Content -Path $source_main -Value $appended_content
          } else {
            Write-Host "Source main.js or index.js (from server) not found"
          }

      - name: Patch main.XXX.js to main.XXX.original.js
        run: |
          $directory = 'FE/resources/app/out/WebServer/ClientApp/dist'
          
          $source_main = Get-ChildItem -Path $directory -Filter "main*" | Where-Object { -not $_.PSIsContainer }
    
          if ($source_main) {
              # Extract original file name without extension
              $originalName = [System.IO.Path]::GetFileNameWithoutExtension($source_main.Name)
              $originalFullPath = $source_main.FullName
        
              # Define the new file name in the format "original-name.original.js"
              $new_main_name = "$originalName.original.js"
        
              # Rename the file
              Copy-Item -Path $originalFullPath -Destination (Join-Path -Path $directory -ChildPath $new_main_name)              
              Write-Host "File renamed from $($source_main.Name) to $(Join-Path -Path $directory -ChildPath $new_main_name)"

              Write-Host "Finding and Replacing now"

              $source_content = Get-Content -Path $originalFullPath -Raw

              $searchText1 = "https://api.getfiddler.com"
              $replaceText1 = "http://127.0.0.1:5678/api.getfiddler.com"
              $updatedText1 = $source_content -replace [regex]::Escape($searchText1), $replaceText1

              $searchText2 = "https://identity.getfiddler.com"
              $replaceText2 = "http://127.0.0.1:5678/identity.getfiddler.com"
              $finalUpdatedText = $updatedText1 -replace [regex]::Escape($searchText2), $replaceText2

              # Overwrite the file with the new content
              Set-Content -Path $originalFullPath -Value $finalUpdatedText

              echo "MAIN_XXX_NAME=$originalName" >> $env:GITHUB_ENV            
          } else {
            Write-Host "No file found starting with 'main' in the specified directory. (Main,XXX.js)"
          }

      - name: Clean msojocs-patch
        run: |
          if (Test-Path msojocs-patch) {
            Remove-Item -Path "msojocs-patch" -Recurse
          } else {
            Write-Host "msojocs-patch Folder not found"
          }
        
      - name: Add patch.json
        run: |
          $patch_json = "FE/resources/app/out/WebServer/patch.json"
          
          $jsonContent = @{
            "ClientApp\\dist\\$env:MAIN_XXX_NAME.js" = @{
              "target" = "ClientApp\\dist\\$env:MAIN_XXX_NAME.original.js"
              "content" = ""
              "cur" = 0
              "start" = 0
              "end" = 1
            }
            "..\\main.js" = @{
              "target" = "..\\main.original.js"
              "content" = ""
              "cur" = 0
              "start" = 0
              "end" = 1
            }
          }

          # Convert the PowerShell object to JSON format
          $jsonString = $jsonContent | ConvertTo-Json -Depth 10

          # Write the JSON string to the file
          $jsonString | Set-Content -Path $patch_json -Encoding UTF8
          
          # Output message
          Write-Host "JSON file created successfully at $patch_json"

      - name: Rename FE 
        id: rename-fe
        run: |
          if (Test-Path FE) {
            $newName = "Fiddler-Everywhere-V$env:PATCHING_VERSION-Patched"
            
            Rename-Item -Path "FE" -NewName $newName
            
            echo "patched-fe-name=$newName" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
          } else {
            Write-Host "FE Folder not found!?"
          }

      - name: Upload Artifact for Patched FE
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.rename-fe.outputs.patched-fe-name }}"
          path: "${{ steps.rename-fe.outputs.patched-fe-name }}/"
          if-no-files-found: error
