# This is a basic workflow to help you get started with Actions

name: Scrape FE Version (All / Latest)

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      is_all:
        type: boolean
        description: whether save all
        required: true
        
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Python Script to scrape all to versions.txt
        if: ${{ inputs.is_all}} = 'true'
        run: python utils/fe-version-scraper/fe-version-scraper.py --all

      - name: Run Python Script to scrape latest version to latest_version.txt
        if: ${{ inputs.is_all}} = 'true'
        run: python utils/fe-version-scraper/fe-version-scraper.py --latest

      - name: Upload all .txt files
        uses: actions/upload-artifact@v4
        with:
          name: version-scrape # The name of the artifact
          path: 'utils/fe-version-scraper/*.txt' # This pattern matches all .txt files in utils/fe-version-scraper/
          if-no-files-found: error # Continue if no .txt files are found (optional)


